name: Generate Snake Animation

on:
  schedule: # Run every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Generate Snake Game from GitHub Contributions
        uses: Platane/snk@v3
        with:
          github_user_name: lucky-arya
          outputs: dist/snake.svg

      - name: Push Snake Animation to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
